rabbitmq/chef-cookbook

Gemfile
Rakefile
recipes/default.rb

- Moved the service enable and start to the bottom of the default recipe so you can change variables around.
- This should resolve #201

Fix for Issue #201

---

attributes/default.rb
recipes/default.rb

Allow the distro version to be optionally pinned.  By default the available distro repo package will be used.

Distro version pinning

---

.gitignore
Gemfile
Gemfile.lock

This is to add a Gemfile.lock so we start standardizing on the Gems we are using for development.

inital enforcement of Gemfile.lock

---

README.md
attributes/default.rb
metadata.rb
spec/default_spec.rb
templates/default/rabbitmq.config.erb

*  add support for looback users

---

libraries/default.rb
recipes/default.rb
spec/default_spec.rb

The module need to remain Opscode or some other type of clever
Chef-named derivative. I also fixed a minor
indenting error.

Fix travis build.

---

CONTRIBUTING.md

This is largely based on the yum cookbook's contribution guide. I
tweaked a few things, but most it seemed good enough to just copy-pasta.
Let me know what you think may or may not be needed.

Update Contributing file with new links and help.

---

libraries/default.rb
recipes/default.rb

The module needs to remain Opscode or some other type of clever
Chef-named derivative.

Change module back to Opscode.

---

recipes/default.rb

As of [PR25](https://github.com/opscode-cookbooks/erlang/pull/25),
yum-epel and yum-erlang_solutions are included by
default for all 'rhel' systems greater than 5.
Tests will fail for this branch until a new release of the Erlang cookbook. I tested
with my Berksfile pointed at master and all was good.

Remove yum-epel case statement.

---

providers/user.rb

Do the same as was done in the above add user case, remove the password from the resource name.

don't put change password in log

---

attributes/default.rb
recipes/default.rb

added attributes that allow configuration of the download url and package name for rabbitmq deb and rpm and esl-erlang-compat rpm, for example for those that do not have the luxury to connect production environments to the outside world.

addition of attributes for downloading deb, rpm and esl-erlang-compat

---

attributes/default.rb
libraries/default.rb
recipes/default.rb
templates/default/rabbitmq.config.erb

Example taken from https://gist.github.com/michaelklishin/3f47bae850bdd9f1a79a

Allow specifying allowed ssl protocol versions via attributes

---

attributes/default.rb
libraries/default.rb
recipes/default.rb
spec/default_spec.rb
templates/default/rabbitmq.config.erb

Allow ssl ciphers to be configured

Added ssl_ciphers

---

providers/plugin.rb

Fix the problem of trying to check for existing plugins but rabbitmq-plugins is not on path yet.
On install and uninstall the path is added but not on checking if the plugin is enabled so on ubuntu12.04 it will fail.

Fix plugin_enabled not having path appended

---

attributes/default.rb
spec/default_spec.rb
templates/default/rabbitmq.config.erb

Implement additional rabbit configs using additional_rabbit_configs attribute, #181.

Additional rabbit configs

---

providers/cluster.rb

This is a known issue in rabbitmq 3.3.4 or earlier, and the `rabbitmqctl` commands always appends `...done.` at the end of outputs, which causes issues in `cluster.rb` when doing join to the cluster.
Please refer to my issue for details: https://github.com/jjasghar/rabbitmq/issues/271
This fix force the command `rabbitmqctl eval "node()."` to always print out the first line which filters out the wrong tail string.
Before
```
[root@prod-rabbitmq-1001 ~]# rabbitmqctl eval "node()."
'rabbit@prod-rabbitmq-1001'
...done.
```
After
```
[root@prod-rabbitmq-1001 ~]# rabbitmqctl eval "node()." | head -1
'rabbit@prod-rabbitmq-1001'
```
I've tested this PR in the latest rabbitmq 3.5.3 and old versions like 3.3.4 and 3.2.3, and everything looks fine.
Thanks!

Fixed 'rabbitmqctl eval' command for old rabbitmq versions

---

providers/cluster.rb

This builds on #267 to add:
- More fixes to catch single quotes from cluster_status, current_cluster_node_type and node_name
- Fixes from #267 the node_name still had single quotes which were removed on L113
- The cluster_status, disc_nodes and ram_nodes functions passed back a match of ["rabbit@rabbit1'","'rabbit@rabbit2"] which contained single quotes from the middle of the match. This was removed L83, L91 and L100
In rare instances, if the cluster_status returns on a non running server or is not clustered yet, the matchers caused no matched and nil errors. Fixes were introduced to pass nil in some functions through and to better handle them specifically with cluster_join:
- Passthrough of nil in some functions
- Additional debug logging and handling of nil responses from functions

Fix single quote and nil issues with cluster recipe

---

providers/cluster.rb

This should resolve the issue in jjasghar/rabbitmq#265 where some node names come back with single-quotes when queried using `rabbitmqctl`

Add patterns to catch where the node name is surrounded by single-quotes

---

metadata.rb
spec/default_spec.rb
templates/default/rabbitmq-env.conf.erb

If attribute node['node']['additional_env_settings'] exists, it is
expected to be an array of strings, which will then be appended
to rabbit-env.conf. This allows users the flexibility to specify
ENV settings that don't have explicit attributes. (E.g. Some
settings may be new to rabbitmq but won't require a recipe update
before people can take advantage of them.)
I also cleaned up a couple of rubocop issues in default_spec.rb

Support additional env args

---

libraries/default.rb
spec/default_spec.rb

Remove the extra curly braces for format_ssl_ciphers

---

libraries/default.rb
spec/default_spec.rb

Current cookbook (my bad) forced the ssl cipher format to be enclosed with single quotes. This turns out to be almost a completely invalid way of specifying ssl ciphers.  This patch removes those quotes and leaves it up to the user to specify ssl ciphers in any of the various formats, like those used in the spec and shown below.
Using erlang style cipher suite configuration, (see output of command rabbitmqctl eval 'ssl:cipher_suites(erlang)', which is lower cases with {}:
node['rabbitmq']['ssl_ciphers'] = %w({ecdhe_ecdsa,aes_256_cbc,sha384} {ecdh_ecdsa,aes_256_cbc,sha384})
Using UPPERCASE cipher constants:
node['rabbitmq']['ssl_ciphers'] = %w("ECDHE-ECDSA-AES256-SHA384" "ECDH-ECDSA-AES256-SHA384")

Allow for flexiable SSL cipher formats

---

attributes/default.rb
recipes/default.rb
spec/default_spec.rb

There are cases where you may want to install rabbitmq, but not start the service immediately.  For instance, when preparing an AMI for AWS, you may want to install all of the software and then when launching the instance only do the configuration.  It is also useful when you want to use systemd instead of the default initd scripts.

Allow the service to be manually managed

---

providers/cluster.rb

Currently some of the methods in the cluster provider are broken because they are using `gsub!` instead of `gsub`, as well as splitting on an array.
This PR fixes it by:
- Using `gsub` instead of `gsub!`
- Removing duplicate `split`

Use gsub instead of gsub!

---

providers/user.rb
recipes/default.rb

When passing a user with name "management" and tag "management", the tag won't be created because in `user_has_tag?` method the tag is considered to be existed. I think it'd be easier only run `rabbitmqctl -q list_user management` as command, and parse the result with ruby regex function like:
cmd.run_command
user_list = cmd.stdout # => "management\t[management test]"
tags = user_list.match(/^#{name}\s+\[(.+*)\]/)[1].split # => ["management", "test"]

Fix user_has_tag? issue when name and tag are the same

---

recipes/default.rb

As mentioned in #245, I do not think the issue of default user/pass changes being disregarded is solved. The fact that notification on the rabbitmq-env.conf template is immediate causes the service to start before the values can be written to the rabbitmq.conf file by the next resource. This changes fixed the problem for me.
I thought perhaps delaying the notifications would cause all sorts of other recipes and LWRP to fail during the initial chef run because the service is not running, but then I noticed that the [service is started](https://github.com/jjasghar/rabbitmq/blob/v4.1.2/recipes/default.rb#L216) down at the bottom of the recipe, so perhaps it is not an issue? It's working for me and my simple wrapper cookbook.

Delay start of RabbitMQ on template changes

---

providers/cluster.rb

I was wondering why on some nodes of my rabbitmq cluster, chef would try to reconfigure the cluster_node_type at every chef-run, resulting in breaking all existing connections to the broker.
The actual reason was a subtle issue while parsing the output of `rabbitmqctl cluster_status` when the node list fits on multiple lines. Read on.
Have a cluster with enough nodes that the list of nodes or running_nodes in the `rabbitmqctl cluster_status` output takes more than one line, like this:
```sh
root@staging3-failover2:~# rabbitmqctl cluster_status
Cluster status of node 'rabbit@staging3-failover2' ...
[{nodes,[{disc,['rabbit@staging3-backends','rabbit@staging3-failover1',
'rabbit@staging3-failover2']}]},
{running_nodes,['rabbit@staging3-backends','rabbit@staging3-failover1', …
```

Fixed rabbitmq cluster_status parsing when node list takes multiple lines.

---

attributes/default.rb

Which will be required by RabbitMQ 3.6.0.

esl-erlang-compat now provides Erlang R16B03-1

---

templates/default/rabbitmq-env.conf.erb

Issue related to this change is here
https://github.com/jjasghar/rabbitmq/issues/250
Setting ulimits for rabbitmq should be done in /etc/default
and not the rabbitmq-env file.

removing ulimit from rabbitmq-env.conf

---

providers/user.rb

This fix removes the following warning:
rabbitmq/providers/user.rb:43: warning: nested repeat operator + and * was replaced with '*': /^sano\s+\[(.+*)\]/

Fix regex in user.rb

---

attributes/default.rb

It makes much more sense than `nil`.

rabbitmq.community_plugins default should be {}

---

attributes/default.rb
templates/default/rabbitmq.config.erb

I wanted to configure `log_levels` of `rabbitmq.config`. But, I can't set it without creating own new cookbook. So, I added log_levels to rabbitmq.config and set it default value, ` [{connection, info}]`
References: https://www.rabbitmq.com/configure.html

enable to configure log_levels

---

templates/default/rabbitmq.config.erb

I'm currently manually managing my cluster, but would like to be able to specify the cluster_partition_handling setting.  This change allows for it to be set without setting use_auto_clustering.

Allow the partition handling to be set even if we are not using auto clustering

---

.rubocop.yml
providers/cluster.rb

cc @michaelklishin @jjasghar 
Tested and working:
```
[2015-12-16T01:26:23+00:00] INFO: Processing rabbitmq_cluster[[{"name":"rabbit@ec2-54-201-251-170.us-west-2.compute.amazonaws.com","type":"disc"}]] action join (gz-rabbitmq::join line 5)
[2015-12-16T01:26:23+00:00] INFO: [rabbitmq_cluster] Action join ...
[2015-12-16T01:26:24+00:00] INFO: DOUDOU => rabbit@ec2-54-201-251-170.us-west-2.compute.amazonaws.com
[2015-12-16T01:26:25+00:00] INFO: [rabbitmq_cluster] Clustering node 'rabbit@ec2-54-200-235-67.us-west-2.compute.amazonaws.com' with 'rabbit@ec2-54-201-251-170.us-west-2.compute.amazonaws.com' ...
[2015-12-16T01:26:26+00:00] INFO: [rabbitmq_cluster] Node rabbit@ec2-54-200-235-67.us-west-2.compute.amazonaws.com joined in rabbit@ec2-54-201-251-170.us-west-2.compute.amazonaws.com with …
```

fix hardcoded --ram node type for cluster join

---

providers/user.rb
recipes/default.rb
spec/default_spec.rb

This PR is aimed to fix the issue which chef-client with a version less than 11.14 complaining about method `sensitive` missing. My current project requires a chef-client version 11.12 for some reasons, and we can't depend on this rabbitmq cookbook because of the version gap in chef-client.
This fix shouldn't affect any other user but make this cookbook fit into older versions of chef client. We've tested it under chef `11.12` and it works perfect!
Refer to: https://github.com/chef/chef/issues/1744 for more details.
Thanks!

NO-REF Check chef client version before calling sensitive

---

providers/user.rb

Original \b matches a word, but a hyphen is not respected, which causes 'user' to match 'user-whatever'. Replacing the \b with \s to match the whitespace instead.

Fix user grep command to match whitespace

---

README.md
attributes/default.rb
libraries/default.rb
providers/cluster.rb
providers/vhost.rb
recipes/cluster.rb
recipes/default.rb
recipes/user_management.rb
spec/default_spec.rb
templates/default/rabbitmq.config.erb

* removed check if clustering enabled in cluster recipes since this should not
be needed
* streamlined clustering attributes
* simplified logic in rabbitmq.config template for clustering
* adapted README
* fixed some rubocop offenses

simplified clustering logic

---

libraries/default.rb
providers/cluster.rb
providers/parameter.rb
providers/plugin.rb
providers/policy.rb
providers/user.rb
providers/vhost.rb

I ran into https://github.com/jjasghar/rabbitmq/issues/334 today when rolling some new Rabbitmq servers. Since the `ShellOut`s are already ensuring the presence of a `HOME` environment variable, it seemed logical to have the `execute` blocks do the same. Agree/disagree/thoughts?
Thanks!

Pass a HOME environment variable to all rabbitmq execute blocks

---

README.md
attributes/default.rb
templates/default/rabbitmq.config.erb

The example demonstrator how using the node attributes we can
add a user with attributes needed to have access to one or more
ghosts.

added an example to the "user_management" section.

---

providers/cluster.rb

The call to `joined_cluster?` was passing in the `to_join` node name
instead of the current node name. This resulted in the nodes trying to
rejoin whenever the `to_join` node was offline.
Resolves #347

Fix check for whether node has joined cluster

---

recipes/default.rb

Ubuntu 15.04 machines will otherwise try to use SystemD.

Use init if job_control uses init.

---

templates/default/rabbitmq.upstart.conf.erb

Related to #338. By default package only rotates logs in /var/log/rabbitmq/*.log. Direct solution is to rename logs names. Other solution is to depend on logrotate cookbook. Dunno which is best.

Package install logrotate for *.log

---

metadata.rb
recipes/default.rb
spec/default_spec.rb

Fixes/Enhancements:
- use `dpkg_autostart` to cleanly prevent dpkg from automatically running RabbitMQ after installation
- Make the Debian installation behave more like RedHat by allowing package upgrades

Debian Fixes

---

attributes/default.rb

This PR matches the example ciphers in the attributes file to the current rspec tests.
https://github.com/jjasghar/rabbitmq/pull/260/commits/4480a86b7b5c8f5a109a4ea9b403493e00ae220f was a backwards compatibility breaking change for me. I'm not sure if it's the version of rabbit that I'm using, but the only valid configuration I get is when the openssl ciphers are double quoted (not single quoted) or the standard cipher strings are wrapped in curly braces. It was previously valid to just specify the cipher suite as an array of strings so long as they weren't in the Openssl format, now they must be an array of curly brace wrapped strings.
These examples would have made it a lot quicker to realise there was a change. 
I would ask that you please increment the metadata version by a major …

Update cipher examples

---

providers/cluster.rb

This change uses a custom exception handler to throw errors in join_cluster().  A exception handler in action :join calls Chef::Application.fatal! to keep the same error functionality as before but an ensure block ensures Rabbit is always restarted.  Resolves #344 
I have not updated metadata as I'm assuming you want to manage that.

Restart Rabbit on cluster join error, resolves #344

---

README.md

As of v4.7.0, the README.md file refers to the following attributes to enable clustering:
- `node['rabbitmq']['clustering']['enabled']`
- `node['rabbitmq']['clustering']['enable']`
After checking the code, I believe that the `enabled` variant is a typo and that the `node['rabbitmq']['clustering']['enable']` attribute should be used everywhere in the documentation.

Fix typo in name of rabbitmq clustering enable attribute

---

.travis.yml
Rakefile
providers/parameter.rb
providers/policy.rb
providers/vhost.rb
recipes/default.rb

Looks like the rake tasks are failing due to a very old version of bundler (1.6.9):
`LoadError: cannot load such file -- bundler/inline`
`bundler/inline` was introduced in version `1.10.0`.

Update bundler that comes with Travis' ruby 2.1.0.

---

providers/cluster.rb
providers/parameter.rb
providers/plugin.rb
providers/policy.rb
providers/user.rb
providers/vhost.rb

Since the `Mixlib::ShellOut` doesn't have a setter for the `environment` attribute, passing the environment via constructor should fix it.

Fixes #375. Assign environment via constructor.

---

spec/spec_helper.rb

Hopefully this will fix some troubles with the Travis CI build.

Fix warning:already initialized constant LOG_LEVEL

---

providers/cluster.rb
recipes/cluster.rb

When using manual clustering in this cookbook, rabbitmq(e.g. rabbit1-ubuntu-1404) starts as a member of a single node cluster named as its own hostname. 
And the current join action will never happen by just skipping with the warning message below.
> [rabbitmq_cluster] Node is already member of rabbit@rabbit1-ubuntu-1404. Joining cluster will be skipped.
This is because the current join action process doesn't consider the current cluster name and only checks if the node is a part of whatever cluster or not.
This PR is to check if the node is a part of the desired cluster defined through the attribute ( node['rabbitmq']['clustering']['cluster_name'] ) so that the join action will happen if the node is a part of the wrong/(in my case, default=hostname) cluster.

Cluster join never happens for manual clustering

---

attributes/default.rb
spec/policy_management_spec.rb

defined policies and disabled_policies as [] to avoid nil:NilClass error

---

attributes/default.rb
templates/default/rabbitmq.config.erb

This commit adds support for changing the management port of the
RabbitMQ management web interface.

Add support for non ssl management port

---

README.md

The issues_url and source_url metadata break Chef 11 support so this cookbook already requires Chef 12+

Update readme to require Chef 12.1

---

attributes/default.rb

Inspired by #414.
@jjasghar any objections? any other places where we need to change that default that I may have missed? (e.g. around tests)

Provision 3.6.8 by default

---

recipes/policy_management.rb

The policy provider accepts the apply_to parameter but the recipe is not passing it in. I've modified and tested the change in production and it works correctly. Screenshot attached.

apply_to parameter missing

---

attributes/default.rb

Policies is a hash
https://github.com/rabbitmq/chef-cookbook/blob/master/recipes/policy_management.rb#L24
This causes an error if you define something like this in a wrapper, without making it an override.
```ruby
default['rabbitmq']['policies']['ha-all']['pattern'] = '^(?!amq\\.).*'
```

Policies Attribute Fix

---

attributes/default.rb

When can't have any logic in it, it is purely a === operator
```
==> rabbitmq-1: SyntaxError
==> rabbitmq-1: -----------
==> rabbitmq-1: /var/chef/cache/cookbooks/rabbitmq/attributes/default.rb:15: syntax error, unexpected <=
==> rabbitmq-1:   when <= '6'
==> rabbitmq-1:          ^
==> rabbitmq-1: /var/chef/cache/cookbooks/rabbitmq/attributes/default.rb:17: syntax error, unexpected '>'
==> rabbitmq-1:   when > '6'
==> rabbitmq-1:         ^
==> rabbitmq-1: /var/chef/cache/cookbooks/rabbitmq/attributes/default.rb:20: syntax error, unexpected keyword_when, expecting end-of-input
==> rabbitmq-1: when 'suse'
```

Fix Case Statement for RHEL

---

providers/parameter.rb
providers/policy.rb

This change allows us to change string variables without actually mutating them.
This allows these files to be compatible with ruby 3.0 in the future.
Ruby 3.0 will have frozen strings, which prevents the `<<` operator from working, because it attempts to mutate a frozen string.
Using the `+=` operator reassigns the original variable instead of mutating it.
Fixes #422

reassign variable with frozen string  instead of appending to it

---

providers/policy.rb

rabbitmqctl set_policy is already an idempotent command, and receiving the same input twice is not harmful.

make set action idempotent

---

.kitchen.dokken.yml
.travis.yml

- Ubuntu needs apt-get update before running tests so that it has the newest package version metadata
- Add debian-8 testing
Fixes the ubuntu test failure seen in https://github.com/rabbitmq/chef-cookbook/pull/427
Note: dokken tests will fail until https://github.com/rabbitmq/chef-cookbook/pull/427 is merged in

Update kitchen dokken

---

README.md
providers/parameter.rb
providers/policy.rb
recipes/policy_management.rb
resources/parameter.rb
resources/policy.rb
test/cookbooks/rabbitmq_test/recipes/lwrps.rb

This cleans up the resource property errors.
Note: This is a breaking change
```
================================================================================
Recipe Compile Error in /opt/kitchen/cache/cookbooks/rabbitmq/resources/parameter.rb
================================================================================
ArgumentError
-------------
Property `params` of resource `rabbitmq_parameter` overwrites an existing method.
Cookbook Trace:
---------------
/opt/kitchen/cache/cookbooks/rabbitmq/resources/parameter.rb:28:in `class_from_file'
Relevant File Content:
----------------------
/opt/kitchen/cache/cookbooks/rabbitmq/resources/parameter.rb:
21:
22:  actions :set, :clear, :list
23:  default_action :set
24:
25:  attribute :parameter, :kind_of => String, :name_attribute => true …
```

Rename params property to parameters

---

libraries/default.rb

When running under Chef client 13, Chef issues an error on the prepend method for the string because the strings are frozen objects.  By moving the whitespace characters to the original array creation, we can do a simple non-destructive join, which solves the issue of not being allowed to change a frozen string in chef.

Update to default.rb library to handle frozen strings

---

.kitchen.dokken.yml

A possible workaround for #435

mount cgroup in docker, even when privileged

---

providers/parameter.rb

apply the same functionality as https://github.com/rabbitmq/chef-cookbook/pull/425, but to parameters.
Since the actual chef resources themselves here are not actually idempotent, it is probably better to actually have a chef guard parse the `list_parameter` output, but since `set_policy` is already being done in this manner, I figured it was acceptable functionality for now.

allow set_parameter changes to existing parameters

---

README.md
libraries/helpers.rb

This adds some helper functions to allow a wrapper cookbook to implement removing a node from a cluster in 2 scenarios:
- removing self from cluster (helpful for normal decommission)
- removing any node from cluster (helpful for abruptly terminated machines)
These both should not be actually consumed in this cookbook and simply be provided for wrappers to use as they see fit. This should be implemented only after careful thought, design, testing, etc.

closes #432

---

recipes/policy_management.rb

Addresses https://github.com/rabbitmq/chef-cookbook/issues/441
We don't have to restart RabbitMQ to apply policies.
The changes in https://github.com/rabbitmq/chef-cookbook/pull/425 will cause these notifications to fire on every Chef run.
Straight from https://www.rabbitmq.com/parameters.html
```
Policies can change at any time. 
When a policy definition is updated, its effect on matching exchanges and queues will be reapplied.
Usually it happens instantaneously but for very busy queues can take a bit of time (say, a few seconds).
```

Do not restart RabbitMQ for Policy Change

---

metadata.rb
recipes/default.rb

The debian rabbitmq-server package relies on `/etc/init.d/rabbitmq-server` to rotate logs. When installing rabbitmq-server, with upstart support, the init script is removed. This prevents the log files from properly rotating.
Add logrotate cookbook, configure logrotate when debian upstart installs.
```
/var/log/rabbitmq/*.log {
weekly
missingok
rotate 20
compress
delaycompress
notifempty
sharedscripts
postrotate
/etc/init.d/rabbitmq-server rotate-logs > /dev/null
endscript
}
```
```
"/var/log/rabbitmq/*.log" {
weekly
rotate 20
missingok
notifempty
delaycompress
sharedscripts
postrotate
/usr/sbin/rabbitmqctl rotate_logs > /dev/null
endscript
}
```

replace logrotate script, for debian upstart

---

recipes/default.rb

We were getting intermittent failures after the erlang cookie was changed.
They looked like this:
```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '69'
---- Begin output of rabbitmqctl stop_app && rabbitmqctl reset && rabbitmqctl start_app ----
STDOUT: Stopping rabbit application on node '3f49a593-39c1-4954-9c38-f3e763cb4ee3@ip-10-72-81-113' ...
STDERR: Error: unable to connect to node '3f49a593-39c1-4954-9c38-f3e763cb4ee3@ip-10-72-81-113': nodedown
DIAGNOSTICS
===========
attempted to contact: ['3f49a593-39c1-4954-9c38-f3e763cb4ee3@ip-10-72-81-113']
3f49a593-39c1-4954-9c38-f3e763cb4ee3@ip-10-72-81-113:
* connected to epmd (port 4369) on ip-10-72-81-113
* epmd reports: node '3f49a593-39c1-4954-9c38-f3e763cb4ee3' …
```

Remediate RabbitMQ reset failures

---

recipes/cluster.rb

https://docs.chef.io/deprecations_resource_cloning.html

Fix resource cloning deprecation warnings

---

attributes/default.rb
recipes/default.rb

What we are noticing is that every time it get reconvered after the VM delete senario it failed once on second attempt it works so adding a retry to start the node, keeping values to defualt so no chang eofr anyone using cookbook but you can override defaults if you wanted to set to something else

Request for adding retry to node start 

---

attributes/default.rb
recipes/default.rb

Fixes #457, addresses [RabbitMQ core team request](https://groups.google.com/forum/#!topic/rabbitmq-users/9ASVq55wXnA) to switch to Bintray/GitHub/Package Cloud from rabbitmq.com.

Make it possible to override base package URL location; switch default to GitHub

---

attributes/default.rb
templates/default/rabbitmq.config.erb

Hello!
I've recently started using your cookbook for rabbitmq. In my case, all servers have public & private networking simultaneously, and I do not want RabbitMQ to listen on public network or `0.0.0.0` as it does by default.
In your cookbook, you already have attributes(and some hacks):
* `node['rabbitmq']['erl_networking_bind_address']`
* `node['rabbitmq']['erl_networking_bind_address']`
* `node['rabbitmq']['kernel']['inet_dist_use_interface']`
But nothing configures ip address for the management console. And I find it strange. I believe it is a pretty demanded option for many people.
e.g. [#442] is a similar issue, but addresses the problem even more globally.
Thank you very much!
P.S. About the tests. I do not see many tests for `rabbitmq.config` syntax and contents. I can cover my …

Listen ip address configuration for management console.

---

attributes/default.rb
recipes/default.rb

Using the same method provided for overriding the base config, allow overriding the env file too.

Allow override of rabbitmq-env template

---

README.md
attributes/default.rb
spec/default_spec.rb
templates/default/rabbitmq.config.erb

Attribute `node['rabbitmq']['ssl_listen_interface']` is set will define specific interface to bind.
May be filled with "0.0.0.0" (this will result in listening on IPv4 interfaces).
Will not affect existing config if left default (`nil`)

Ability to set interface to listen for SSL connections

---

providers/cluster.rb

previously it was using the node type of the first node in the cluster
as the node type for each node in the cluster.

fixed change cluster node type

---

attributes/default.rb
spec/default_spec.rb
templates/default/rabbitmq.config.erb

This adds support for a several more TLS socket options to ensure
that the recommendations/setup from http://www.rabbitmq.com/ssl.html#tls-evaluation-tools is
possible to achieve with this cookbook.
Closes #240.

Expose more TLS socket options, enable them by default

---

attributes/default.rb
spec/default_spec.rb
templates/default/rabbitmq.config.erb

This PR makes TCP buffer size and credit flow defaults configurable, as requested in #459.
Closes #459.

Make TCP buffer size configurable

---

README.md
attributes/default.rb
spec/default_spec.rb
templates/default/rabbitmq.config.erb

This PR makes it possible to override TCP listener interface.
The attributes used mimic those for TLS listeners. This
is not optimal because there is no way to set multiple
listeners, so this is something that is worth revisiting in 6.0.
Closes #364.

Make it possible to override TCP listener interface

---

recipes/default.rb
spec/default_spec.rb

This adds a directory resource that creates config root, as requested in #351.
Closes #351.

Add a config root resource, closes #351

---

attributes/default.rb
libraries/default.rb
recipes/default.rb
templates/default/rabbitmq-env.conf.erb

This change is to update line #18 in `templates/default/rabbitmq-env.conf.erb` to append the `.config` suffix to the value of `node['rabbitmq']['config']`
As per https://github.com/rabbitmq/chef-cookbook/blob/v5.x/recipes/default.rb#L237 the generated config file will always be at `#{node['rabbitmq']['config']}.config` and not at simply `node['rabbitmq']['config']`
Without this change `rabbitmq-env.conf` will never properly handle a non-default setting for the value of `node['rabbitmq']['config']`

append `.config` to rabbitmq-env.conf.erb `CONFIG_FILE` line

---

libraries/default.rb
providers/parameter.rb
providers/policy.rb
providers/user.rb
recipes/default.rb

* add method to parse 'rabbitmq-server' package version from automatic
ohai attributes
* add ohai attribute reload after installing rabbitmq-server package to
allow usage of before mentioned logic in the same chef-client run
* introduce version comparison using 'Gem::Version.new()' to allow
correct comparison of semver compatible version strings

simplify version specific switchcase for rabbitmqctl commands

---

CONTRIBUTING.md
README.md
attributes/default.rb
test/erlang_package/latest_deb/default_spec.rb
test/erlang_package/latest_rpm/default_spec.rb
test/erlang_package/pinned_deb/default_spec.rb
test/erlang_package/pinned_rpm/default_spec.rb
test/integration/cluster/default_spec.rb
test/integration/default/default_spec.rb
test/integration/limits/default_spec.rb
test/integration/lwrps/default_spec.rb
test/integration/management_plugin/default_spec.rb

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were unable to be fixed. Please review them to see if they can be manually resolved.
* http://lists.chef.io/sympa/info/chef (301) with 1 occurrences could not be migrated:  
([https](https://lists.chef.io/sympa/info/chef) result ConnectTimeoutException).
* http://lists.chef.io/sympa/info/chef-dev (301) with 2 occurrences could not be migrated:  
([https](https://lists.chef.io/sympa/info/chef-dev) result ConnectTimeoutException).
* http://sample.com/rabbitmq_community_plugin.ez (404) with 2 occurrences could not be migrated:  
([https](https://sample.com/rabbitmq_community_plugin.ez) result …

URL Cleanup

---

attributes/default.rb

Queues matching this pattern are e.g. `amq.direct` and do not contain an
actual `\` character.
The current example policy pattern looks wrong. However, I am not 100% certain.

Fix policy pattern typo

---

providers/plugin.rb

Use new method installed_rabbitmq_version to simplify switchcases
for plugins command.

simplify switchcase for rabbitmq plugins command

---

README.md

Fix a typo in the README on custom package download locations for RPM-based packages.
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._
No tests run, as it's only a README change.

Fix README typo on rpm package attribute

---

metadata.rb
providers/user.rb

This is just a tiny change that quotes the password when being passed to the execute resource for the change password operation. Otherwise a special character like "&" at the beginning of the password will break the command execution.

Setting a password starting with "&" fails

---

providers/erlang_apt_repository_on_bintray.rb
providers/erlang_package_from_bintray.rb

Change `pin_priority` to a string to be compatible with the [apt cookbook](https://supermarket.chef.io/cookbooks/apt). While [the native resource](https://docs.chef.io/resource_apt_preference.html) (introduced in Chef 13.3) supports both strings and integers, the [old apt cookbook](https://github.com/chef-cookbooks/apt/blob/v5.1.0/resources/preference.rb#L31) only supports strings.
I'm forced to use Chef 12 currently, and version 5.1.0 of the apt cookbook. I confirmed that changing this to strings resolves the issue.
Should affect very few users.
Here's the error from chef:
```
Chef::Exceptions::ValidationFailed
----------------------------------
Option pin_priority must be a kind of [String]!  You passed 800.
```

Use strings for pin_priority to be compatible with the apt cookbook

---

providers/erlang_package_from_bintray.rb

Hi, this is as much a question as a possible solution. It does not appear that erlang-ftp and erlang-tftp are available for Ubuntu 16.04 (xenial) in the rabbitmq-erlang repository.
The files `erlang-ftp_21.3.8.2-1_amd64.deb` and `erlang-tftp_21.3.8.2-1_amd64.deb` are available for [bionic](https://dl.bintray.com/rabbitmq-erlang/debian/pool/erlang/21.3.8.2-1/ubuntu/bionic/), but not for [xenial](https://dl.bintray.com/rabbitmq-erlang/debian/pool/erlang/21.3.8.2-1/ubuntu/xenial/).
I don't know what these packages are used for in RabbitMQ, but from what I can gather, things appear to be working without them.
Please tell me if I'm doing something wrong. :)
Fixes this error:
```
* rabbitmq_erlang_package_from_bintray[rabbitmq_erlang] action install
* apt_package[erlang-base, erlang-mnesia, …
```

Don't install erlang-ftp and erlang-tftp to fix xenial

---

attributes/default.rb
templates/default/rabbitmq.config.erb

Added the ability to configure channel_max attribute
This changes were made to enable max channels per connection in my company.

Support channel max attribute

---

.kitchen.dokken.yml
.kitchen.yml
attributes/default.rb

Update the openSUSE form  `opensuse-leap-42.3` to  `leap 15.1`
`leap 42.3` was discontinued the  [Jul 1st 2019](https://en.opensuse.org/Lifetime) 
I have tested it using docker:
```
KITCHEN_LOCAL_YAML=.kitchen.dokken.yml  kitchen converge  rabbitmq-erlang-latest-suse-opensuse-leap-15
...
* service[rabbitmq-server] action start (up to date)
* ohai[reload_packages] action reload
- re-run ohai and merge results into node attributes
Running handlers:
Running handlers complete
Chef Infra Client finished, 8/21 resources updated in 15 seconds
Finished converging <rabbitmq-erlang-latest-suse-opensuse-leap-15> (0m17.62s).
-----> Test Kitchen is finished. (0m22.11s)
```

 Update openSUSE to leap 15

---

.kitchen.dokken.yml
recipes/default.rb

This PR is to keep idempotency of this cookbook.
The ohai 'reload_packages' do nothing when no package is installed but still report that some resources are changed.## Types of Changes
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._
If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

fix idempotency

---

attributes/default.rb

Logrotate option `delaycompress` has no effect without `compress`. This PR simply adds the `compress` option to the list of default options.
From the [man page](https://linux.die.net/man/8/logrotate):
>Postpone compression of the previous log file to the next rotation cycle. **This only has effect when used in combination with compress.** It can be used when some program cannot be told to close its logfile and thus might continue writing to the previous log file for some time.
mailing list. We're here to help! This is simply a reminder of …

Add compress to logrotate options

---

providers/cluster.rb

Fixes #548
Default rabbitmqctl output formatting changed to "table" in RabbitMQ 3.8
Need to explicitly specify "erlang" formatting when getting
cluster_status in order to properly parse output.
Fixes non-idempotency of `rabbitmq::cluster` recipe on RabbitMQ 3.8.
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

[#548] Specify output formatting when getting cluster_status on RabbitMQ 3.8

---

recipes/default.rb

Without this, it doesn't properly run ``installed_rabbitmq_version`` and causes
an error:
```
* ohai[reload_packages] action nothing (skipped due to action :nothing)
Recipe: rabbitmq::management_ui
* rabbitmq_plugin[rabbitmq_management] action enable
================================================================================
Error executing action `enable` on resource 'rabbitmq_plugin[rabbitmq_management]'
================================================================================
NoMethodError
-------------
undefined method `[]' for nil:NilClass
Cookbook Trace: (most recent call first)
----------------------------------------
/tmp/kitchen/cache/cookbooks/rabbitmq/libraries/default.rb:79:in `installed_rabbitmq_version'
/tmp/kitchen/cache/cookbooks/rabbitmq/providers/plugin.rb:26: …
```

Add missing notifies for ohai[reload_packages] on Fedora/RHEL
