.kitchen.yml, Berksfile, README.md, metadata.rb, recipes/default.rb, spec/default_spec.rb, spec/policy_management_spec.rb, spec/spec_helper.rb
This should turn on CentOS7 support for rabbitmq
=> CentOS 7 support

providers/user.rb
change the typo "comand" to "command"
=> Fix command error in provider/user.rb

providers/user.rb, resources/user.rb
=> Support rabbitmq_user with multiple vhosts.

providers/cluster.rb
See more details in issue #285
=> Fix exception when first node is launched. Fixes issue #285

attributes/default.rb, spec/default_spec.rb
=> Upgrade to -3_all.deb

attributes/default.rb, spec/default_spec.rb
=> Revert "Upgrade to -3_all.deb"

metadata.rb
Found this while browsing the source:
https://github.com/jjasghar/rabbitmq/blob/d10c7a8334491002cccc3508571a7d4dcaa0cb0e/attributes/default.rb#L36
=> Update metadata.rb with config_template_cookbook

libraries/matchers.rb
Closes #342
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jjasghar/rabbitmq/371)
=> Fix set_cluster_name ChefSpec matcher

templates/default/rabbitmq.config.erb
=> fix cluster_nodes config line syntax when using auto clustering

recipes/default.rb
- A new dependancy for RabbitMQ
=> Added socat

README.md, attributes/default.rb, spec/policy_management_spec.rb
This is intended to address issue #287
=> Comments out example HA policy attributes

metadata.rb
=> Add opensuse / opensuseleap to the metadata

.travis.yml, metadata.rb, resources/user.rb, resources/vhost.rb, test/integration/cluster/rspec/Gemfile, test/integration/cluster/rspec/cluster_spec.rb, test/integration/default/rspec/Gemfile, test/integration/helpers/rspec/Gemfile, test/integration/helpers/rspec/rabbitmq_spec.rb, test/integration/helpers/rspec/spec_helper.rb, test/integration/lwrps/rspec/Gemfile, test/integration/lwrps/rspec/lwrps_spec.rb
makes it easier to migrate to inspec later ;)
I've also added travis for all branches again.
=> Serverspec 2 upgrade

spec/default_spec.rb
Updated matcher for `upgrade_dpkg_package`.
=> Updated spec for upgrade_dpkg_package

attributes/default.rb
```  ================================================================================
Recipe Compile Error in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/rabbitmq/attributes/default.rb
================================================================================
NoMethodError
-------------
undefined method `[]' for nil:NilClass
```
Cookbook is pulled in as a dependency even on windows hosts, which don't have
LSB attributes. It makes sense to recover gracefully in that case.
If English isn't your first language, don't worry about it and try to
communicate the problem you are trying to solve to the best of your abilities.
As long as we can understand the intent, it's all good.
_Put an `x` in the boxes that …
=> Handle missing lsb attributes

providers/erlang_package_from_bintray.rb
The Ubuntu packager tries to satisfy dependencies when `erlang-base` is installed.  Since this occurred before the other `erlang-*` packages are pinned, this causes incompatible versions to be installed.  This PR updates the logic to manage all Debian packages at the same time.
While messing around in the provider code, I noticed the removal logic for non-debian platforms stuck inside the debian block.
=> Fix Ubuntu Erlang Install Issue

recipes/users.rb
=> Always set user tagging

recipes/default.rb
Make sure we're calling ::File not Chef::File
Signed-off-by: Tim Smith <tsmith@chef.io>
=> Scope the File exist conditional properly

attributes/default.rb, recipes/default.rb
Invalid platforms were being passed here. I wrote a cookstyle to catch this in the future.
Signed-off-by: Tim Smith <tsmith@chef.io>
=> Fix invalid value_for_platform helper usage

.kitchen.dokken.yml, .kitchen.yml, .travis.yml, bin/ci/install_chef_dk.sh
Signed-off-by: Tim Smith <tsmith@chef.io>
=> Fix license acceptance in Travis

resources/erlang_apt_repository_on_bintray.rb, resources/erlang_package_from_bintray.rb, resources/erlang_yum_repository_on_bintray.rb, resources/erlang_zypper_repository_on_suse_factory.rb, test/cookbooks/rabbitmq_test/recipes/default.rb
More fixes based on the latest rules I've developed in Cookstyle
=> Additional Cookstyle fixes

providers/plugin.rb
It appears that ruby-2.7 (which ships with Chef 16) likely doesn't like
``0022`` as an integer and is causing issues on Chef 16. To workaround the
issue, we can simply change this to a string.
The following is the output of the original error I've been hitting.
```
Recipe: rabbitmq::management_ui
* rabbitmq_plugin[rabbitmq_management] action enable
* execute[rabbitmq-plugins enable rabbitmq_management] action run
================================================================================
Error executing action `run` on resource 'execute[rabbitmq-plugins enable rabbitmq_management]'
================================================================================
TypeError
---------
no implicit conversion from nil to integer
Resource Declaration:
---------------------
37:     execute …
```
=> Fix Chef 16 issue with plugin resource

providers/user.rb
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._
=> Fix backlash handling on permissions
